### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by pdugas** [backuppc/cygwin-rsyncd#6]
For your consideration...  A github action to build the installer, create a release and attach it when you create `v*` tags.
```
# .github/workflows/release.yml
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NSIS
        run: sudo apt update && sudo apt install -y nsis
      - name: Build Installer
        run: makensis -V4 backuppc_rsync-server.nsi
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.exe
          asset_name: installer.exe
          asset_content_type: application/vnd.microsoft.portable-executable
```
